version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:20.17

jobs:
  build:
    - checkout

    - attach_workspace:
        at: .

    - run:
        name: Build Project for Production
        command: yarn build
        environment:
          NODE_ENV: production

  install-dependencies:
    - checkout

    - restore_cache:
        keys:
          - v1-node-deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}-{{ checksum "prisma/schema.prisma" }}
          - v1-node-deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          - v1-node-deps-{{ checksum "package.json" }}
          - v1-node-deps

    - run:
        name: Install Node Dependencies
        command: yarn

    - run:
        name: Generate Prisma Types
        command: yarn prisma generate

    - save_cache:
        key: v1-node-deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}-{{ checksum "prisma/schema.prisma" }}
        paths:
          - node_modules

    - persist_to_workspace:
        root: .
        paths:
          - node_modules

  lint:
    - checkout

    - attach_workspace:
        at: .

    - run:
        name: Lint Project
        command: yarn lint

workflows:
  build-lint:
    jobs:
      - install-dependencies:
          executor: node
          filters:
            tags:
              only: /.*/

      - lint:
          executor: node
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/

      - build:
          executor: node
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
